// Login
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const USER_SIGN_IN = 'USER_SIGN_IN';

//Error
export const ERROR_HANDLING = 'ERROR_HANDLING';

//Map
export const LOCATION = 'LOCATION';
export const CURR_LOCATION = 'CURR_LOCATION';

//INCIDENT
export const LATEST_INCIDENT_ADDED = 'LATEST_INCIDENT_ADDED';
export const ALL_INCIDENTS = 'ALL_INCIDENTS';
export const INCIDENTS_LOADING = 'INCIDENTS_LOADING';
