// Login
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const GET_USER_AUTH_FIREBASE = 'GET_USER_AUTH_FIREBASE';
export const ADD_USER_FIREBASE = 'ADD_USER_FIREBASE';
export const SIGN_OUT = 'SIGN_OUT';

//Error
export const ERROR_HANDLING = 'ERROR_HANDLING';

//Map
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const CURR_LOCATION = 'CURR_LOCATION';

//INCIDENT
export const LATEST_INCIDENT_ADDED = 'LATEST_INCIDENT_ADDED';
export const ALL_INCIDENTS = 'ALL_INCIDENTS';
export const INCIDENTS_LOADING = 'INCIDENTS_LOADING';
export const USERS_INCIDENTS = 'USERS_INCIDENTS';
export const VIEW_INCIDENT = 'VIEW_INCIDENT';
export const NOTIFICATION_INCIDENTS = 'NOTIFICATION_INCIDENTS';
export const TOGGLE_DOMAINS = 'TOGGLE_DOMAINS';

//Emergency places
export const EMERGENCY_PLACES_HOSPITALS = 'EMERGENCY_PLACES_HOSPITALS';
export const EMERGENCY_PLACES_POLICE_STATIONS =
	'EMERGENCY_PLACES_POLICE_STATIONS';
export const EMERGENCY_PLACES_LOADING = 'EMERGENCY_PLACES_LOADING';
export const NEARBY_PLACES_GOOGLE_URL =
	'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=';

//Settings
export const SET_EMERGENCY_RADIUS = 'SET_EMERGENCY_RADIUS';
export const SET_NOTIFICATION_TIMEOUT = 'SET_NOTIFICATION_TIMEOUT';
export const SET_NOTIFICATION_RADIUS = 'SET_NOTIFICATION_RADIUS';
export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';

//Introduction slides
export const SHOW_INTRO = 'SHOW_INTRO';
