// Login
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const GET_USER_AUTH_FIREBASE = 'GET_USER_AUTH_FIREBASE';
export const ADD_USER_FIREBASE = 'ADD_USER_FIREBASE';

//Error
export const ERROR_HANDLING = 'ERROR_HANDLING';

//Map
export const LOCATION = 'LOCATION';
export const CURR_LOCATION = 'CURR_LOCATION';

//INCIDENT
export const LATEST_INCIDENT_ADDED = 'LATEST_INCIDENT_ADDED';
export const ALL_INCIDENTS = 'ALL_INCIDENTS';
export const INCIDENTS_LOADING = 'INCIDENTS_LOADING';
export const USERS_INCIDENTS = 'USERS_INCIDENTS';
